### ISSUE TITLE
States order

### ISSUE THREAD

**Issue by peikk0** [nazco/i3status-modules#1]
Hi,

Is there a way to order states? Right now they appear in that order: critical, ok, unknown, warning, and it's not a logical order, I would prefer : ok, warning, critical, unknown (0, 1, 2, 3)

Cheers.

**Comment by nazco** [comment]
Well, I know that problem but py3status calls the functions in a module in alphabetic order (as far as I know) so it ins't that easy to make it configurable without spliting it to multiple modules. But I will look forward to make it possible. A workaround could be to add a prefix like a[1-4] to each function.

**Comment by peikk0** [comment]
Thanks, I'll use the workaround in mean in the mean time. :)

**Comment by nazco** [comment]
Hey, you may like the new icinga_simple.py module. This module only checks on status at a time and you need (not so beautiful) redundant config definitions in your i3status.conf but with this module you can set the colors and the order individually.

**Comment by peikk0** [comment]
Thanks, I'll keep yours anyway, I've done a few modifications already. :) https://github.com/peikk0/dotfiles/blob/master/.i3/py3status-modules/icinga.py
